run: "./run"
results: "./results"

fastq_dir: "/scratch/jmartens/vera/results/fastq"
genome_dir: "/scratch/slrinzema/snake/genomes"

first_genome: "/scratch/slrinzema/snake/genomes/hg38"
first_assembly: "hg38"

second_genome: "/scratch/slrinzema/snake/genomes/Human_papillomavirus"
second_assembly: "HPV_metagenome"