run: "./run"
results: "./results"
fastq_dir: "/vol/rimlstemp/molbio/martens/slrinzema/fastq/fastq/"
samplesheet: "./samples.tsv"

genome_dir: "./genomes"
first_assembly: "hg38"
second_assembly: "HPV_metagenome"

merge_replicates: True